CREATE DATABASE GOWIII;
cardsUSE GOWIII;

CREATE TABLE Users(
id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(100),
email VARCHAR(100),
password VARCHAR(100));

CREATE TABLE Cards(
id INT PRIMARY KEY,
imagen VARCHAR(900),
title VARCHAR(100),
description VARCHAR(900));

CREATE TABLE Characters(
id INT PRIMARY KEY,
imagen VARCHAR(900),
title VARCHAR(100),
description VARCHAR(900));

DROP TABLE Cards;


INSERT INTO Cards VALUES(1,"http://images1.wikia.nocookie.net/__cb20120711153805/godofwar/es/images/d/d9/Espadas_de_Atenea.png","Espadas de Atenea","Dadas a Kratos por Atenea después de haber destruido al antiguo Dios de la Guerra Ares, éstas son las armas principales de Kratos como Dios de la Guerra. Mientras que Kratos es un dios, las Espadas de Atenea emiten un aura amarilla y son de color dorado con glifos de color azul debido al poder de dios que residía en kratos.");
INSERT INTO Cards VALUES(2,"https://pm1.narvii.com/6275/6a2339a6e1fc79fbf6108450db16f18df72c6f1b_hq.jpg","Espadas del Exilio","Las Espadas del Exilio sustituyen a las Espadas de Atenea como sus armas principales, ya que éstas últimas, que recibió como Dios de la Guerra, fueron destruidas por el rayo de Zeus. Las espadas nuevas también tienen un diseño ligeramente diferente, pero su modelo no cambia al subir de nivel.");
INSERT INTO Cards VALUES(3,"http://pm1.narvii.com/6506/077b39c7872082af0382a5cca151ba76f689cdae_00.jpg","Arco de Apolo","Lo obtiene luego de matar a Pirítoo, el amante mortal de Perséfone, que ha sido encarcelado en el Inframundo por Hades y condenado a pasar toda la eternidad atrapado en una jaula de zarzas. Este elemento tiene movimientos similares a la Perdición de Tifón, excepto que usa fuego en lugar de viento.");
INSERT INTO Cards VALUES(4,"https://i.ytimg.com/vi/HR9TzSFZ_-E/maxresdefault.jpg","Espadas del Caos","Le son dadas por Ares, el dios de la guerra, cuando Kratos se compromete a ser siervo de éste. Son un par de cuchillas curvas unidas por cadenas a los antebrazos de Kratos, dándole la capacidad de arrojarlas a gran distancia. Desprenden brillos amarillos o rojos cuando se utilizan.");
INSERT INTO Cards VALUES(5,"https://i.pinimg.com/originals/29/53/3e/29533e0967faa2fb6b24eb3a9aa42d8a.jpg","Espada del Olimpo","Es una gran espada de energía extremadamente poderosa que al llenarla de energía, desprende una luz azul brillante. Fue creada por Zeus, forjada de los Cielos y la Tierra durante la Gran Guerra para desterrar a los Titanes al Tártaro, y poner fin a la guerra de una vez por todas.");
INSERT INTO Cards VALUES(6,"http://2.bp.blogspot.com/_gEOW7Hlr3EM/TPSDon4ek5I/AAAAAAAAABc/X2AjMOFRLkk/s1600/hades580.jpg","Garras de Hades","Permiten a Kratos convocar a las almas de los muertos. Con ellas, Kratos puede extraer el alma de sus enemigos, atacando éstas al resto de sus enemigos. Tienen un ataque similar al del Martillo Bárbaro, que permiten a Kratos convocar las almas de los enemigos con los que está luchando.");
INSERT INTO Cards VALUES(7,"https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/i/f513721e-793b-4fb7-9b25-ea0c1cbb06cf/ddrzrx7-e0d896bc-c0cd-4804-9c37-8502ba839a7c.png","Cestus de Nemea","Al final Kratos se los arrebata y los usa para derrotarlo. Después van a ser importantes por ser la única arma que destruye el Ónice, un tipo de roca que aparece con frecuencia en el juego, en forma de escudos, muros y armaduras. Por lo tanto, es la única arma capaz de matar a Escorpio, como el cuerpo de la criatura es en parte Ónice.");
INSERT INTO Cards VALUES(8,"https://i.ytimg.com/vi/wlAmVMwkf6o/maxresdefault.jpg","Látigo de Némesis","Fue hecho a mano por el dios herrero Hefesto, su material es la Piedra del Ónfalos que Kratos adquirió de las entrañas de Cronos después de matarlo. El arma simula una garra de tres puntas afiladas y extensas, que pueden reubicarse instantáneamente como una aspa filosa y agredir con rápidos y repetidos cortes al mismo tiempo.");
INSERT INTO Cards VALUES(9,"https://i.ytimg.com/vi/MsX5VklTLqc/maxresdefault.jpg","Desagravio Divino","Las Espadas de Atenea tienen una, llamada Desagravio Divino. Tras la activación de esta habilidad, Kratos empuña la Espada del Olimpo y la clava sobre la tierra haciendo que se cree un masivo torbellino a su alrededor, dañando a cualquier enemigo que este cerca. Zeus utilizó este ataque contra los titanes para poner fin a la Gran Guerra.");
INSERT INTO Cards VALUES(10,"https://i.ytimg.com/vi/t3n8lDS0qF4/maxresdefault.jpg","Invocación de Almas","La Invocación de Almas es una magia de las Garras de Hades. Permite a Kratos poder invocar a las almas de los enemigos que había matado durante su búsqueda. Se utilizan como aliados para matar a soldados y otras criaturas a su alrededor.");
INSERT INTO Cards VALUES(11,"http://4.bp.blogspot.com/_pnCDyHM5_pE/TJ_sOOHKecI/AAAAAAAAABw/Dumal8nchBo/s1600/God-of-War-3.jpg","Rugido de Nemea","Es una magia que proviene de los Cestus de Nemea. Permite a Kratos crear ondas de energía golpeando los cestus contra el suelo, tirando a los enemigos en su camino. Después del Ejército de Esparta, esta es la magia más fuerte del juego.");
INSERT INTO Cards VALUES(12,"https://i.ytimg.com/vi/wlAmVMwkf6o/maxresdefault.jpg","Ira de Némesis","La Ira de Némesis es un poder disponible al usar el Látigo de Némesis. Consiste en electrificar a los enemigos con rayos, dándole a Kratos la oportunidad de golpear a sus enemigos. Es muy útil en batallas contra varios enemigos. Este poder es similar a la Furia de Cronos y a la Ira de Poseidón.");


INSERT INTO Characters VALUES(1,"https://img.ibxk.com.br/2018/04/20/20190302793802.jpg","Kratos","Hijo del dios Zeus y Calisto, una mujer mortal, Kratos nació en Esparta, una ciudad griega que se caracterizaba por ser un pueblo guerrero. Kratos sirvió a Ares lealmente. Atacó pueblos y extendió el caos en su nombre.");
INSERT INTO Characters VALUES(2,"https://i.ytimg.com/vi/59ijRpWjAcI/maxresdefault.jpg","Zeus","Zeus era el rey de los dioses, gobernante del Monte Olimpo y Dios del cielo y los relámpagos. Zeus era el hijo de los Titanes Cronos y Rea, y el más joven pero más fuerte de todos sus hermanos. Fue Zeus quien llevó a sus hermanos y hermanas a la batalla contra los Titanes");
INSERT INTO Characters VALUES(3,"https://i.pinimg.com/originals/7f/49/52/7f4952dce04ff68a667d75ea81cf9bb8.jpg","Cronos","Cronos era el líder y también el más joven de la primera generación de titanes. Durante el reinado de Urano, el cielo, los Hecatonquiros y los Cíclopes fueron encerrados en el Tártaro, causando una gran dolor hacia Gaia. Ella creó una hoz de piedra para que uno de sus hijos Titanes pudiera matar a Urano.");
INSERT INTO Characters VALUES(4,"http://i.imgur.com/QyoX3kF.png","Atenea","Atenea, también conocida como Palas Atenea, es la diosa de la civilización, la guerra, la sabiduría, la fuerza, la estrategia, artesanía, la justicia, y la habilidad. Atenea es también una compañera astuta de los héroes y la diosa del esfuerzo heroico. Es la diosa patrona Virgen de Atenas.");
INSERT INTO Characters VALUES(5,"https://bokugamer.files.wordpress.com/2015/05/god-of-war-iii-playstation-3-ps3-185.jpg","Hefesto","Hefesto es el dios del fuego y la fragua, así como de los herreros, los artesanos, los escultores, los metales y la metalurgia. Hefesto era hijo de Hera, sin la cooperación de Zeus. Hera lo engendró sola, celosa porque Zeus había dado a luz a Atenea, que había brotado de su cabeza.");
INSERT INTO Characters VALUES(6,"https://i.ytimg.com/vi/IwoKmIJ12wo/maxresdefault.jpg","Pandora","Pandora fue la primera mujer sobre la tierra, hecha por orden de Zeus para introducir males en la vida de los hombres, después de que Prometeo, yendo en contra de su voluntad, les otorgara el don del fuego. Pandora fue enviada a Epimeteo, quien se sintió feliz de tenerla como esposa.");
INSERT INTO Characters VALUES(7,"https://i.pinimg.com/originals/c2/c5/94/c2c594d1e038be172a464f60ab54dd92.jpg","Afrodita","Afrodita era la diosa del amor, la belleza y la sexualidad. Fue a causa de su belleza que los otros dioses temían celos que interrumpiría la paz entre ellos, y los llevaría a la guerra. Entonces Zeus la casó con Hefesto, a quien el resto de los dioses no veían como una amenaza.");
INSERT INTO Characters VALUES(8,"https://i.ytimg.com/vi/fsBjVEo6r3Y/maxresdefault.jpg","Gaia","Gaia era la diosa principal que personificaba la tierra. Ella era una deidad antigua primordial y era considerada la diosa de la madre de toda la vida. Ella nació de Caos, presentándose como la fundación eterna de dioses del Olimpo. Ella creó al dios Urano, el cielo estrellado, que era también su igual.");
INSERT INTO Characters VALUES(9,"https://i.pinimg.com/originals/37/93/23/37932307d80357dda6ad58451336bd87.jpg","Hades","Hades, el dios del inframundo, era hijo de los titanes Crono y Rea. Tenía tres hermanas, Deméter, Hestia y Hera, así como dos hermanos, Zeus y Poseidón. Juntos constituían los seis dioses olímpicos originales. Tras hacerse adulto, Zeus logró obligar a su padre a que regurgitase a sus hermanos.");
INSERT INTO Characters VALUES(10,"https://i.ytimg.com/vi/Tr4R-j3-oCo/maxresdefault.jpg","Poseidon","Poseidón es el dios del mar, las tormentas y, como agitador de la tierra, de los terremotos. Poseidón fue protector de muchas ciudades helenas, aunque perdió el concurso por Atenas tras competir contra Atenea. Cuando se enfadaba o era ignorado, hendía el suelo con su tridente y provocaba manantiales caóticos, terremotos, hundimientos y naufragios");
INSERT INTO Characters VALUES(11,"https://i.ytimg.com/vi/DLxdm_UOwHo/maxresdefault.jpg","Helios","Helios es la personificación del Sol. Helios era el dios que todo lo ve era invocado a menudo como testigo en los juramentos. Era hijo de los titanes Hiperión y Tea, y hermano de las diosas Selene, la luna, y Eos, la aurora. Imaginado como un hermoso dios coronado con la aureola del sol, cada día traía la luz al mundo en su carro");
INSERT INTO Characters VALUES(12,"https://i.ytimg.com/vi/R6zdc0mnXGQ/maxresdefault.jpg","Hercules","Heracles era considerado hijo de Zeus y Alcmena, una reina mortal, hijo adoptivo de Anfitrión y nieto de Perseo por la línea materna. n un ataque de locura provocado por Hera, Heracles mató a sus propios hijos y a dos de sus sobrinos con sus propias manos.");
